// Auto-generated by generateMsgId task. DO NOT EDIT.
package com.rainnov.framework.proto;

public final class MsgId {

    private MsgId() {}

    public static final class LOGIN {
        public static final int LOGIN_REQ = 1001;
        public static final int LOGIN_RESP = 1002;
        public static final int LOGOUT_REQ = 1003;
        public static final int LOGOUT_RESP = 1004;
    }

    public static final class SYSTEM {
        public static final int HEARTBEAT_REQ = 1;
        public static final int HEARTBEAT_RESP = 2;
    }
}
